spring:
  config.activate.on-profile:
    sql.init.platform: postgresql
    datasource:
      hikari.maximum-pool-size: 5
      url: jdbc:log4jdbc:postgresql:thin:@localhost:5432:postgres
      username: 'postgres'
      password: '4865'
    jpa:
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      properties.hibernate.format_sql: true
    data.jpa.repositories.bootstrap-mode: lazy